module ml_tests.Tests.InternalOperationsTests

open NUnit.Framework
open mini_ml_tests.Parser

[<TestFixture>]
type BinaryOperationsTests () =
    
    [<TestCase("head [3, 4]", "3")>]
    [<TestCase("tail [3, 4]", "[4]")>]
    [<TestCase("head [true, true, false]", "true")>]
    [<TestCase("tail [false, true, false]", "[true, false]")>]
    [<TestCase("not true", "false")>]
    [<TestCase("not false", "true")>]
    [<TestCase("not (not true)", "true")>]
    [<TestCase("not (not false)", "false")>]
    [<TestCase("not (not (not true))", "false")>]
    [<TestCase("not (not (not false))", "true")>]
    [<TestCase("empty []", "true")>]
    [<TestCase("empty [1]", "false")>]
    [<TestCase("empty [1, 2]", "false")>]
    [<TestCase("not (empty [1, 2])", "true")>]
    [<TestCase("not (head [1, 2] != 1)", "true")>]
    [<TestCase("head [1, 2] == 1", "true")>]
    [<TestCase("head [true, false] && false", "false")>]
    [<TestCase("fst (true, false)", "true")>]
    [<TestCase("snd (true, false)", "false")>]
    [<TestCase("fst (1, 2)", "1")>]
    [<TestCase("snd (1, 2)", "2")>]
    [<TestCase("fst ('a', 2)", "'a'")>]
    [<TestCase("snd ((1, 2), 2)", "2")>]
    [<TestCase("snd (fst ((1, true), 2))", "true")>]
    member this.TestInternalReduction(actual: string, expected: string) =
        reduce_equals actual expected
    
    [<TestCase("head [3, 4]", "num")>]
    [<TestCase("tail [3, 4]", "List<num>")>]
    [<TestCase("head [true, true, false]", "bool")>]
    [<TestCase("tail [false, true, false]", "List<bool>")>]
    [<TestCase("not true", "bool")>]
    [<TestCase("not false", "bool")>]
    [<TestCase("not (not true)", "bool")>]
    [<TestCase("not (not false)", "bool")>]
    [<TestCase("not (not (not true))", "bool")>]
    [<TestCase("not (not (not false))", "bool")>]
    [<TestCase("empty []", "bool")>]
    [<TestCase("empty [1]", "bool")>]
    [<TestCase("empty [1, 2]", "bool")>]
    [<TestCase("not (empty [1, 2])", "bool")>]
    [<TestCase("not (head [1, 2] != 1)", "bool")>]
    [<TestCase("head [1, 2] == 1", "bool")>]
    [<TestCase("fst (1, 3)", "num")>]
    [<TestCase("snd (1, 3)", "num")>]
    [<TestCase("fst (true, false)", "bool")>]
    [<TestCase("snd (true, false)", "bool")>]
    [<TestCase("fst (1, true)", "num")>]
    [<TestCase("snd (1, true)", "bool")>]
    [<TestCase("fst (true, 1)", "bool")>]
    [<TestCase("snd (true, 1)", "num")>]
    [<TestCase("fst (1, 3) == 1", "bool")>]
    [<TestCase("snd (1, 3) == 3", "bool")>]
    [<TestCase("fst (true, false) && false", "bool")>]
    [<TestCase("fst ('a', false)", "char")>]
    [<TestCase("fst (5 + 5, 'b')", "num")>]
    [<TestCase("snd ((1, 3), ('c', true))", "pair<char,bool>")>]
    [<TestCase("fst ((1, 3), ('c', true))", "pair<num,num>")>]
    [<TestCase("head", "(List<a> -> a)")>]
    [<TestCase("tail", "(List<a> -> List<a>)")>]
    [<TestCase("not", "(bool -> bool)")>]
    [<TestCase("empty", "(List<a> -> bool)")>]
    [<TestCase("fst", "(pair<a,b> -> a)")>]
    [<TestCase("snd", "(pair<a,b> -> b)")>]    
    member this.TestTypes(actual: string, expected: string) =
        type_equals actual expected    
